[build]
command = "npm run build"
publish = "personalai/build"

[dev]
  targetPort = 5000 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on